### ISSUE TITLE
Unable to sync full chain

### ISSUE THREAD

**Issue by deh8551** [aeternity/aeternity#3216]
## Expected Behavior
I have been trying to sync the complete blockchain without success.  If I try to sync from scratch, it fails at block 90981 with the message:
2020-04-13 16:18:20.824 [info] <0.32380.10>@aec_sync:post_blocks:828 Failed to add synced block 90981: {root_hash_mismatch,<<228,86,214,63,238,221,23,148,72,243,194,69,160,208,231,224,107,17,11,94,75,228,59,248,22,176,52,181,216,28,146,75>>,<<100,50,114,193,119,215,13,202,56,222,70,143,116,15,74,172,133,188,147,22,106,171,249,149,66,83,80,239,24,155,2,214>>}...

If I try to sync from the latest backup https://aeternity-database-backups.s3.eu-central-1.amazonaws.com/mnesia_main_v-1_latest.tgz  it fails immediately with the next block to be synced

aeternity_sync.log
2020-04-13 16:44:04.484 [info] <0.2009.0>@aec_sync:post_blocks:828 Failed to add synced block 239902: {root_hash_mismatch,<<56,75,56,176,153,14,215,64,246,248,135,215,233,161,52,91,255,203,61,152,125,135,202,145,49,27,91,53,110,199,78,194>>,<<85,158,220,136,76,127,127,202,237,50,102,125,121,201,158,94,20,10,156,43,120,70,178,68,137,27,199,240,216,96,53,30>>}
.
.
.
2020-04-13 16:44:05.012 [debug] <0.1525.0>@aec_sync:get_next_work_item:403 Get block at height 239902
2020-04-13 16:44:05.013 [debug] <0.1943.0>@aec_sync:do_fetch_generation_ext:927 we don't have the block -fetching ("<<74,98,182,133,...,144,86,30,0>>")
2020-04-13 16:44:05.021 [debug] <0.1808.0>@aec_sync:do_fetch_generation_ext:927 we don't have the block -fetching ("<<186,68,82,3,...,75,13,141,122>>")
2020-04-13 16:44:05.041 [debug] <0.1725.0>@aec_sync:do_fetch_generation_ext:940 block fetched from "pp_2R7a7JH...k4ms5mV" ("<<122,209,68,69,...,84,3,124,167>>"); "#block{height=239904, root_hash=<<88,235,80,90,...,11,120,183,5>>, prev_hash=<<151,107,68,123,...,38,152,10,244>>}"
.
.
.
2020-04-13 16:44:05.173 [debug] <0.1943.0>@aec_sync:do_fetch_generation_ext:940 block fetched from "pp_NPrJPXf...cbK2BDD" ("<<74,98,182,133,...,144,86,30,0>>"); "#block{height=239902, root_hash=<<85,158,220,136,...,216,96,53,30>>, prev_hash=<<188,66,249,210,...,120,29,137,237>>}"
.
.
.
2020-04-13 16:44:05.455 [info] <0.1943.0>@aec_sync:post_blocks:828 Failed to add synced block 239902: {root_hash_mismatch,<<56,75,56,176,153,14,215,64,246,248,135,215,233,161,52,91,255,203,61,152,125,135,202,145,49,27,91,53,110,199,78,194>>,<<85,158,220,136,76,127,127,202,237,50,102,125,121,201,158,94,20,10,156,43,120,70,178,68,137,27,199,240,216,96,53,30>>}

## Actual Behavior

Sync the whole chain
...

## Steps to Reproduce the Problem

  1. ...
  1. ...
  1. ...

## Logs, error output, etc.

*`aeternity.yaml` 
```
fork_management:
    network_id: "ae_mainnet"


chain:
    # Write chain data to disk.
    persist: true
    # Chain persistence directory relative to application root
    db_path: ./data/
    # Database ending, rocksdb, mnesia, leveled
    db_backend: rocksdb
    # section describing reward split
    protocol_beneficiaries: ["ak_UVxs...vp:100"]
    protocol_beneficiaries_enabled: true

sync:
    # Internal port used for P2P communication
    port: 3115
    # Port used for P2P communication
    # Make sure this port is reachable from you public facing IP.
    # It will be the same as the `port` option if not specified.
    external_port: 3015
    # The listen address should be publicly accessible
    listen_address: 0.0.0.0
    # If the UPnP / NAT-PMP service should be started
    upnp_enabled: false
    # Ping retry configuration in milliseconds
    ping_interval: 30000
    # Number of acceptors in listening pool
    acceptors: 10
    # Connection timeout in miliseconds
    connect_timeout: 1000
    # Maximum time for receiving a ping in miliseconds
    first_ping_timeout: 30000
    # Maximum time for noise handshake in miliseconds
    noise_hs_timeout: 5000
    # Maximum time for the peer to close a connection cleanly
    close_timeout: 3000
    # "Maximum number of inbound connections after which inbound connection are temporary (only used for a single ping)
    max_inbound: 100
    # The maximum number of incoming connections
    max_inbound_hard: 150
    # Maximum number of outbound connections
    max_outbound: 100
    # If the extra outbound connections should be to nodes from different address groups (IP netmask /16)
    single_outbound_per_group: true
    # Maximum number of retries at resolving the host name of untrusted peers.
    resolver_max_retries: 7
    # Waiting time intervals (milliseconds) before each retry at resolving the host name of peers (both trusted and untrusted).
    resolver_backoff_times: [5000, 15000, 30000, 60000, 120000, 300000, 600000]
    # Allowed height difference from current top for incoming blocks (via gossip)
    gossip_allowed_height_from_top: 1

keys:
    dir: keys
    peer_password: "......."

mempool:
    # Number of blocks before inactive TXs are garbage collected
    tx_ttl: 256
    # Number of blocks before invalid (TTL or low nonce) TXs are garbage collected
    invalid_tx_ttl: 5
    # Mempool (re-)synchronization interval (in ms)
    sync_interval: 1800000
    # Maximum nonce offset accepted
#    nonce_offset: 5
    # Maximum nonce accepted when pubkey is not present in state
#    nonce_baseline: 1

http:
    cors:
        # List of domains allowed to access resources
        allow_domains: ["*"]
        # List of headers allowed to be used with requests
        allow_headers: ["*"]
        # List of methods allowed to be used when accessing resources
        allow_methods: ["DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT"]
        # Indicates for how many seconds the results of a preflight request can be cached
        max_age: 1800
    external:
        # Port used for external HTTP API
        port: 3013
        # The external listen address should be publicly accessible
        listen_address: 0.0.0.0
        # Timeouts in milliseconds
        request_timeout: 1000
        # Less than request_timeout
        connect_timeout: 100
        # Number of acceptors in server pool
        acceptors: 10
    internal:
        # The internal listen address should be not publicly accessible
        listen_address: 0.0.0.0
        port: 3113
        # Number of acceptors in server pool
        acceptors: 10
        # Enable (true) debug api. Disabled (false) by default
        debug_endpoints: false
    cache:
        # Enable HTTP cache headers (ETag and Expire)
        enabled: false
        # Time (in seconds) after a block is considered aged. That is an Expire header is generated for such blocks API endpoints.
        aged_blocks_time: 86400
        # Time (in seconds) to cache aged blocks, the Expire header time relative to block creation time.
        aged_blocks_cache_time: 86400

websocket:
    channel:
        listen_address: 0.0.0.0
        port: 3014
        # Number of acceptors in channels WebSocket HTTP server pool
        acceptors: 10

mining:
    # Start mining automatically.
    autostart: false
    beneficiary: "ak_UVxs...vp"

logging:
    # Controls the overload protection in the logs.
    hwm: 50
    # Sets the level of logging.
    level: debug
```

## Specifications

  - Virtualization: Container
 - OS: [*distribution, version*]
  - Node Version: 5.5.1
