### ISSUE TITLE
Cann't mining by my fully synced node + stratum enabled

### ISSUE THREAD

**Issue by cryptooliko** [aeternity/aeternity#3849]
## Expected Behavior
To be able to mining by use stratum server
...

## Actual Behavior
stratum: enabled; true is set the node config file
I get {"error":[-32000,"Invalid request",null],"id":1,"jsonrpc":"2.0","result":null}
...

## Steps to Reproduce the Problem

From fully synced node, set stratum: enabled: true and mining: autostart: true ant try send some work to it (I used lolMiner and/or Gminer)

## Configuration, logs, error output, etc.

- `aeternity.yaml` configuration file

```
mining:
  beneficiary: "ak_23giX78vyoAG..........P"
  autostart: true
stratum:
  enabled: true
  connection:
    host: 0.0.0.0
    port: 9999
    max_connections: 1024
    num_acceptors: 100
  session:
    extra_nonce_bytes: 4
    initial_share_target: 115790322390251417039241401711187164934754157181743688420499462401711837019160
    max_share_target: 115790322390251417039241401711187164934754157181743688420499462401711837020160
    desired_solve_time: 30
    max_solve_time: 60
    share_target_diff_threshold: 5.0
    max_jobs: 20
    msg_timeout: 15
  reward:
    reward_last_rounds: 2  # how many mining epochs to reward
    beneficiaries: [ "ak_23giX78vyoAG.........P:100"]
    keys:
      dir: stratum_keys

logging:
  # Sets the level of logging.
  level: debug

sync:
  # "Maximum number of inbound connections after which inbound connection are temporary (only used for a single ping)
  max_inbound: 100
  # The maximum number of incoming connections
  max_inbound_hard: 150
  # Maximum number of outbound connections
  max_outbound: 100
```

- `log/aestratum.log` log file - plus other related logs, e.g. `log/aeternity_sync.log`, `log/aeternity_mining.log`; if it’s long, please paste to https://ghostbin.com/ and insert the link here.

```
2022-02-02 14:57:42.340 [info] <0.1774.4> new_client_connection, ip: {x,x,x,x}, port: 41750
2022-02-02 14:57:42.341 [error] <0.1774.4> recv_msg_error, reason: invalid_msg, id: 1
2022-02-02 14:57:42.342 [info] <0.1774.4> send_error_rsp, rsp: #{data => null,id => 1,method => undefined,reason => invalid_msg,type => rsp}
2022-02-02 14:57:42.358 [info] <0.1774.4> handle_conn_timeout, phase: connected
2022-02-02 14:57:42.359 [info] <0.1774.4> close_session
```

- from clien side:
```
192.168.000.231.46318-x.x.x.x.09999: {"id":1,"method":"mining.subscribe","params":["GMiner/2.75",null,"x.x.x.x","9999"]}
x.x.x.x.09999-192.168.000.231.46318: {"error":[-32000,"Invalid request",null],"id":1,"jsonrpc":"2.0","result":null}
```

## Specifications

  - Virtualization: container from aeternity/aeternity:v6.4.0
  - Hardware specs:
    * RAM: 32
    * CPU: 16
