### ISSUE TITLE
Invalid configuration schema?

### ISSUE THREAD

**Issue by dincho** [aeternity/aeternity#4223]
## Expected Behavior

No errors, exit code 0.

## Actual Behavior

Errors, exit code 1.

Note that the node actually boots and runs fine.

## Steps to Reproduce the Problem

  1. add the example configuration
  1. ```bin/aeternity check_config data/aeternity_config_schema.json```

## Configuration, logs, error output, etc.

- `aeternity.yaml` configuration file

```
---
chain:
  persist: true
  db_path: "/data/db1"
  db_direct_access: true
fork_management:
    network_id: aehc_demo_parent
http:
    external:
        port: 3013
    internal:
        port: 3113
include_default_peers: false
keys:
    dir: keys
    peer_password: secret
logging:
    level: warning
mempool:
    tx_ttl: 40
metrics:
    host: 127.0.0.1
    port: 8125
mining:
    autostart: true
    beneficiary: ak_2iBPH7HUz3cSDVEUWiHg76MZJ6tZooVNBmmxcgVK6VV8KAE688
    cuckoo:
        edge_bits: 29
        miners:
        -   executable: mean29-avx2
            extra_args: -t 1
peers: []
sync:
    port: 3015
```

```
Validation failed
Position: $schema
Value   :
---SNIP SCHEMA DUMP--
Reason  : No extra properties allowed
Configuration error (validation_failed)
```

## Specifications

  - OS: linux
  - Node Version: 6.11.0
