### ISSUE TITLE
Breaking change in protocol files configuration

### ISSUE THREAD

**Issue by dincho** [aeternity/aeternity#4320]
```
chain:
  persist: true
  db_direct_access: true
  db_path: "/data/db1"
  hard_forks:
    "5": 0 
      #height: 0
      #accounts_file: .iris/aehc_demo_accounts.json
      #contracts_file: .iris/aehc_demo_contracts.json
```

Node 6.13.0 requires the above commented configuration to take into account accounts and contracts files. The `"5": 0" configuration defaults seems to not account for default location of the files correctly.

This is backward compatibility change which could cause major confusion of custom networks operators.
