### ISSUE TITLE
Devmode not producing microblocks unless `emit_mb` explicitly triggered

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aeternity#4326]
## Expected Behavior

Node in devmode should mine transaction without calling http://localhost:3313/emit_mb

## Actual Behavior

Node in devmode starts to mine transactions only after calling http://localhost:3313/emit_mb.

## Steps to Reproduce the Problem

```yaml
version: '3'
services:
  node:
    image: aeternity/aeternity:v6.13.0-bundle
    ports: [3013:3013, 3313:3313]
    volumes:
      - ./aeternity.yaml:/home/aeternity/node/aeternity.yaml
```

```yaml
system:
  dev_mode: true
  plugins:
    - name: aeplugin_dev_mode

dev_mode:
  keyblock_interval: 5
  microblock_interval: 1
  auto_emit_microblocks: false

chain:
  persist: false
  genesis_accounts:
    ak_21A27UVVt3hDkBE5J7rhhqnH5YNb4Y1dqo4PnSybrH85pnWo7E: 1000000000000000000000
```

```js
import { AeSdk, Node, MemoryAccount } from '@aeternity/aepp-sdk'; // @13.3.0

const aeSdk = new AeSdk({
  nodes: [{ name: '', instance: new Node('http://localhost:3013') }],
  accounts: [
    new MemoryAccount('9ebd7beda0c79af72a42ece3821a56eff16359b6df376cf049aee995565f022f840c974b97164776454ba119d84edc4d6058a8dec92b6edc578ab2d30b4c4200'),
  ],
});

await aeSdk.spend(1, aeSdk.address).catch((error) => console.log(error.message));

await fetch('http://localhost:3313/emit_mb');
console.log('mb emitted');

await aeSdk.getHeight();
await aeSdk.spend(1, aeSdk.address);
console.log('spend works');
```

## Configuration, logs, error output, etc.

```
$ node reproduction.mjs
v3/transactions/th_iMF6nKDXmgXwdr3qWg5wPYyUkd9YAanvaRoLtzSV4jVp4RgUX error: Transaction not found
mb emitted
spend works
```

```
node-1  | 14:42:43.744 [info] Acceptors default: 1
node-1  | 14:42:43.747 [info] New key block - height: 1
node-1  | 14:42:43.749 [info] Dev mode handler ready on port 3313
node-1  | 14:42:43.749 [info] ensure_started(aeplugin_dev_mode) -> {ok,[sext,jobs,parse_trans,setup,hut,exometer_core,ssl,ranch,yamerl,aeutils,sha3,jsx,unicode_util_compat,idna,inets,inet_cidr,inet_ext,aetx,aeserialization,getopt,aebytecode,aevm,ecli,aecli,aecore,ebip39,eaex10,epbkdf2,ec_utils,aedevmode,aeplugin_dev_mode]}
node-1  | 14:42:48.751 [info] New key block - height: 2
node-1  | 14:42:49.135 [info] Tx pool events hashes: [<<"th_iMF6nKDXmgXwdr3qWg5wPYyUkd9YAanvaRoLtzSV4jVp4RgUX">>]
node-1  | 14:42:53.755 [info] New key block - height: 3
node-1  | 14:42:58.761 [info] New key block - height: 4
node-1  | 14:43:03.764 [info] New key block - height: 5
node-1  | 14:43:05.067 [info] New micro block - height: 5, 0 txs
node-1  | 14:43:05.155 [info] Tx pool events hashes: [<<"th_4fFbnGCJpEwUMPPCvsqnLBShmkMSH5KCP1eA3pfdHpYMThkTA">>]
node-1  | 14:43:06.072 [info] New micro block - height: 5, 1 txs
node-1  | 14:43:07.078 [info] New micro block - height: 5, 0 txs
node-1  | 14:43:08.082 [info] New micro block - height: 5, 0 txs
node-1  | 14:43:08.771 [info] New key block - height: 6
node-1  | 14:43:09.088 [info] New micro block - height: 6, 0 txs
node-1  | 14:43:10.091 [info] New micro block - height: 6, 0 txs
node-1  | 14:43:11.096 [info] New micro block - height: 6, 0 txs
node-1  | 14:43:12.099 [info] New micro block - height: 6, 0 txs
node-1  | 14:43:13.104 [info] New micro block - height: 6, 0 txs
node-1  | 14:43:13.776 [info] New key block - height: 7
node-1  | 14:43:14.108 [info] New micro block - height: 7, 0 txs
node-1  | 14:43:15.112 [info] New micro block - height: 7, 0 txs
```
So, the first transaction th_iMF6nKDXmgXwdr3qWg5wPYyUkd9YAanvaRoLtzSV4jVp4RgUX is ignored.
The second transaction th_4fFbnGCJpEwUMPPCvsqnLBShmkMSH5KCP1eA3pfdHpYMThkTA gets mined after the first micro block is manually triggered.

Related PRs https://github.com/aeternity/aeternity/pull/4303 https://github.com/aeternity/aeternity/pull/4325
