### ISSUE TITLE
Can't override network id using env variable

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aeternity#4351]
I've run node this way:
```yaml
services:
  node:
    image: aeternity/aeternity:v7.0.0
    ports:
      - "3013:3013"
    environment:
      - AE__FORK_MANAGEMENT__NETOWRK_ID=ae_test
      - AE__HTTP__ENDPOINTS__DRY_RUN=false
```
According to the node's documentation

> The OS environment variables are applied after reading any provided config file, so can be used to override a static user configuration.

https://docs.aeternity.io/en/stable/configuration/

In the node logs I found
```
node-1  | 05:22:17.589 [info] aeu_env:read_config()-> ok
node-1  | 05:22:17.590 [info] Setup phase [normal] 101
node-1  | 05:22:17.595 [info] OS env config: [{"AE__HTTP__ENDPOINTS__DRY_RUN",[<<"http">>,<<"endpoints">>,<<"dry-run">>],"false"}]
node-1  | 05:22:17.595 [info] Map for OS env config: #{<<"http">> => #{<<"endpoints">> => #{<<"dry-run">> => false}}}
node-1  | 05:22:17.595 [info] validation: update_config, result: {ok,[#{<<"http">> => #{<<"endpoints">> => #{<<"dry-run">> => false}}}]}
node-1  | 05:22:17.596 [info] aeu_env:apply_os_env()-> #{<<"http">> => #{<<"endpoints">> => #{<<"dry-run">> => false}}}
node-1  | 05:22:17.596 [info] Setup phase [normal] 102
```
After I executed
```
$ curl http://localhost:3013/v3/status | jq .network_id
"ae_mainnet"
```
So, the network id didn't get changed
